---
title: Express og villumeðhöndlun
---

## Express og villumeðhöndlun

### Vefforritun

### Ólafur Sverrir Kjartansson, [osk@hi.is](mailto:osk@hi.is)

---

## Villumeðhöndlun

* Við skilgreinum villumeðhöndlunar middleware með auka argument
  * `function (err, req, res, next)`
* Skilgreind seinast í app, á eftir öllum öðrum middleware
* Sér um að taka til, logga villu, senda notanda villuskilaboð o.sfr.

***

## 404 villur

* Getum nýtt okkur middleware til þess að grípa 404 villur
  * Verið að reyna að opna route sem við höfum ekki skilgreint
* Setjum middleware á _eftir_ öllum routes sem við vitum að muni aðeins keyra ef ekkert hefur sent reponse
  * En samt á undan villumeðhöndlun

***

<!-- eslint-disable no-unused-vars, no-undef -->

```javascript
app.use((req, res, next) => {
  res.status(404).send('404 Not Found');
});

app.use((err, req, res, next) => {
  console.error(err);
  res.status(500).send('Error occured');
});
```

***

* Ef við endum í 404 middleware, vitum við að ekkert route „að ofan“ höndlaði `request`
  * Þ.a.l. skilum við `404 Not Found`
  * Getum bæðið sent `req` áfram úr dýnamísku route ef ekkert fannst, eða höndlað í route
* Ef við sendum `Error` hlut í `next()` mun villumeðhöndlunar route taka við því

***

<!-- eslint-disable no-unused-vars, no-undef -->

```javascript
app.get('/error', (req, res) => {
  throw new Error('Villa!');
});

app.use((err, req, res, next) => {
  console.error(err);
  res.status(500).send('Villa!');
});
```

---

## Express async await

* Ef við notum `async await` í Express middleware þurfum við að passa upp á að grípa villur
* Getum gert per middleware eða búið til _higher-order fall_ sem sér almennt um
* Sama pæling og með að keyra „main“ fall í dæmum í fyrirlestri 1

***

<!-- eslint-disable no-undef, implicit-arrow-linebreak -->

```javascript
async function asyncMW(req, res, next) {
  // ...
  next();
}

/**
 * Wrap an async function with error handling
 * @params {function} fn Function to wrap
 * @returns {Promise} Promise w/error handling
 */
function catchErrors(fn) {
  return (req, res, next) =>
    fn(req, res, next).catch(next);
}
app.get('/', catchErrors(asyncMW));
```
