---
title: Promises
---

## Promises

### Vefforritun

### Ólafur Sverrir Kjartansson, [osk@hi.is](mailto:osk@hi.is)

---

## Promises & Node.js

* Node.js hefur stuðning við promises sem gerir það auðveldara að vinna með async kóða
* Frá og með útgáfu 8 getum við notað `util.promisify` til að breyta callback API í promise API
* Frá og með útgáfu 14 getum við notað `fs/promises` fyrir promise API ofan á `fs`

***

## util.promisify

```javascript
const util = require('util');
const fs = require('fs');

const readFileAsync = util
  .promisify(fs.readFile);

readFileAsync('data.txt')
  .then((data) => {
    console.log(data.toString('utf8'));
  })
  .catch((err) => {
    console.error(err);
  });
```

***

## async & await

* Getum notað `async` og `await` sem getur flatt kóðann okkar
* Verðum að hafa `async` fall utan um kóða, t.d. með `main` falli
  * Þangað til í nodejs 14.8 þegar stuðning við _top level await_ var bætt við _ef_ við notum ES modules
* Það fall verður að promise, þurfum að setja `catch` á það til að grípa allar villur

***

* Verðum að passa að nota `async` og `await` á réttum stöðum og með `try catch`
* `Promise` eru truthy, getur komið okkur í vandræði!

***

```javascript
const util = require('util');
const fs = require('fs');

const rfAsync = util.promisify(fs.readFile);
async function main() {
  let data = '';
  try {
    data = await rfAsync('data.txt');
  } catch (e) {
    console.error('error', e);
  }
  console.log(data.toString('utf8'));
}
main()
  .catch((err) => { console.error(err); });
```

***

```javascript
const fs = require('fs/promises');

async function main() {
  let data = '';
  try {
    data = await fs.readFile('data.txt');
  } catch (e) {
    console.error('error', e);
  }
  console.log(data.toString('utf8'));
}
main()
  .catch((err) => { console.error(err); });
```

***

## Villur sem ekki eru gripnar

* Ef við skrifum forrit sem nota promises og `async await` er líklegt að villa verði ekki meðhöndluð á einhverjum tímapunkti
* Fáum `UnhandledPromiseRejectionWarning` frá Node.js
  * Í framtíðinni mun það stöðva keyrslu á forriti

***

## `unhandledRejection`

* Node.js skilar frá sér [`unhandledRejection`](https://nodejs.org/api/process.html#event-unhandledrejection) atburð þegar þetta á sér stað
* Getum gripið með `process.on('unhandledRejection', (reason, p) => { /* ... */ })`
* Ættum aðeins að nota til að logga og debugga, [forritið okkar verður komið í óskilgreinda stöðu](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly)
